"use client";

import React, { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FileText, Link as LinkIcon, Calculator, Users, ArrowUpRight, ShieldCheck, CheckCircle2, Clock3, Plus, ChevronRight, Sparkles, LockKeyhole } from "lucide-react";
import { Navbar } from "@/components/Navbar";
import ScrollRevealText from "@/components/animations/ScrollRevealText";
import { ContainerTextFlip } from "@/components/ui/container-text-flip";
import { api } from "@/lib/api";
import { formatDate } from "@/lib/utils";

function SectionHeading({ icon: Icon, eyebrow, title, action }: { icon: React.ElementType; eyebrow: string; title: string; action?: React.ReactNode }) {
  return <div className="flex items-start justify-between gap-4 border-b border-slate-100 pb-4"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-teal-50 text-teal-700"><Icon className="size-4" /></span><div><p className="eyebrow">{eyebrow}</p><h2 className="mt-1 text-base font-semibold tracking-[-0.02em] text-slate-950">{title}</h2></div></div>{action}</div>;
}

export default function DashboardPage() {
  const router = useRouter();
  const [user, setUser] = useState<any>(null); const [documents, setDocuments] = useState<any[]>([]); const [urlChecks, setUrlChecks] = useState<any[]>([]); const [reports, setReports] = useState<any[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { async function loadData() { try { const u = await api.getMe(); setUser(u); const [docs, urls, reps] = await Promise.allSettled([api.getDocuments(), api.getUrlChecks(), api.getReports()]); if (docs.status === "fulfilled") setDocuments(docs.value || []); if (urls.status === "fulfilled") setUrlChecks(urls.value || []); if (reps.status === "fulfilled") setReports(reps.value || []); } catch { router.push("/login"); } finally { setLoading(false); } } loadData(); }, [router]);
  const handleLogout = async () => { await api.logout(); router.push("/login"); };
  if (loading) return <div className="flex min-h-screen items-center justify-center bg-slate-50"><div className="flex flex-col items-center gap-4 text-sm text-slate-500"><span className="size-8 animate-spin rounded-full border-2 border-teal-700 border-t-transparent" />Verifying your secure session</div></div>;
  const sharedWithMe = reports.filter((r) => r.isSharedWithMe);
  const firstName = user?.displayName?.split(" ")[0] || "there";

  return <div className="min-h-screen bg-slate-50"><Navbar user={user} onLogout={handleLogout} /><main className="mx-auto w-full max-w-[1440px] px-4 py-8 sm:px-6 lg:px-10 lg:py-12">
    <div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Your private financial workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] text-slate-950 sm:text-4xl">Good to see you, {firstName}.</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-500">Bring clarity to the paperwork behind your biggest decisions. Everything you need, in one calm place.</p></div><div className="flex items-center gap-2 text-xs text-slate-500"><span className="flex size-7 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><LockKeyhole className="size-3.5" /></span>Private by design</div></div>

    <section className="relative overflow-hidden rounded-3xl bg-slate-950 px-6 py-8 text-white shadow-xl shadow-slate-900/10 sm:px-10 sm:py-10"><div className="absolute -right-24 -top-28 size-80 rounded-full bg-teal-400/15 blur-3xl" /><div className="relative max-w-3xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-3 py-1.5 text-[11px] font-medium text-teal-100"><Sparkles className="size-3.5 text-teal-300" />Understand before you sign</div><ContainerTextFlip words={["Read the fine print.", "Ask better questions.", "Decide with confidence.", "Keep family aligned."]} className="text-3xl font-semibold tracking-[-0.04em] text-white sm:text-5xl" duration={3000} /><p className="mt-5 max-w-xl text-sm leading-6 text-slate-300">Turn a loan document into a clear, human-readable view of costs, conditions, and questions worth asking.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/analyze" className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-xs font-semibold text-slate-950 shadow-sm transition-transform hover:-translate-y-0.5"><FileText className="size-4 text-teal-700" />Analyze a document<ArrowUpRight className="size-3.5" /></Link><Link href="/check-link" className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/5 px-4 py-3 text-xs font-semibold text-white hover:bg-white/10"><LinkIcon className="size-4 text-teal-300" />Check a loan link</Link></div></div></section>
    <ScrollRevealText />

    <div className="mt-8 grid grid-cols-1 gap-6 xl:grid-cols-[minmax(0,1.6fr)_minmax(300px,0.9fr)]"><div className="flex flex-col gap-6">
      <section className="surface-card p-5 sm:p-6"><SectionHeading icon={FileText} eyebrow="Document intelligence" title="Recent analyses" action={<Link href="/analyze" className="inline-flex items-center gap-1.5 rounded-lg bg-teal-50 px-3 py-2 text-xs font-semibold text-teal-800 hover:bg-teal-100"><Plus className="size-3.5" />New analysis</Link>} />{documents.length === 0 ? <div className="flex flex-col items-center justify-center gap-3 py-12 text-center"><span className="flex size-12 items-center justify-center rounded-2xl bg-slate-50 text-slate-400"><FileText className="size-5" /></span><p className="text-sm font-medium text-slate-700">Your first document starts here</p><p className="max-w-xs text-xs leading-5 text-slate-400">Upload a sanction letter or loan offer to see what deserves your attention.</p><Link href="/analyze" className="mt-1 text-xs font-semibold text-teal-700 hover:text-teal-900">Upload a document <ChevronRight className="inline size-3" /></Link></div> : <div className="divide-y divide-slate-100">{documents.slice(0, 4).map((doc) => <div key={doc.id} className="flex items-center justify-between gap-4 py-4 first:pt-5"><div className="min-w-0"><div className="flex items-center gap-2"><p className="truncate text-sm font-semibold text-slate-800">{doc.originalFilename}</p><span className="shrink-0 rounded-md bg-slate-100 px-1.5 py-0.5 text-[10px] font-bold text-slate-500">{doc.detectedMimeType?.includes("pdf") ? "PDF" : "DOCX"}</span></div><p className="mt-1 text-xs text-slate-400">Uploaded {formatDate(doc.createdAt)} · {(doc.sizeBytes / 1024).toFixed(0)} KB</p></div>{doc.latestAnalysisId ? <Link href={`/analyze/${doc.latestAnalysisId}`} className="inline-flex shrink-0 items-center gap-1 rounded-lg bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-teal-50 hover:text-teal-800">View report<ChevronRight className="size-3.5" /></Link> : <span className="inline-flex shrink-0 items-center gap-1 text-xs font-medium text-amber-700"><Clock3 className="size-3.5" />Processing</span>}</div>)}</div>}</section>
      <section className="surface-card p-5 sm:p-6"><SectionHeading icon={LinkIcon} eyebrow="Safety check" title="Recent loan links" action={<Link href="/check-link" className="text-xs font-semibold text-teal-700 hover:text-teal-900">Check a link <ArrowUpRight className="inline size-3.5" /></Link>} />{urlChecks.length === 0 ? <div className="py-8 text-center text-xs text-slate-400">No links checked yet. Verify an online loan website for risk signals.</div> : <div className="divide-y divide-slate-100">{urlChecks.slice(0, 4).map((chk) => <div key={chk.id} className="flex items-center justify-between gap-4 py-4"><div className="min-w-0"><p className="truncate font-mono text-xs font-medium text-slate-700">{chk.submittedUrl}</p><p className="mt-1 text-xs text-slate-400">{formatDate(chk.createdAt)}{chk.claimedEntity ? ` · ${chk.claimedEntity}` : ""}</p></div><Link href={`/check-link?id=${chk.id}`} className="shrink-0 text-xs font-semibold text-teal-700">View result <ChevronRight className="inline size-3" /></Link></div>)}</div>}</section>
    </div>
    <aside className="flex flex-col gap-6"><section className="surface-card p-5 sm:p-6"><SectionHeading icon={Users} eyebrow="Shared with you" title="Family Circle" action={<Link href="/family" className="text-xs font-semibold text-teal-700">Manage</Link>} />{sharedWithMe.length === 0 ? <div className="mt-5 rounded-xl bg-slate-50 p-5"><p className="text-sm font-semibold text-slate-700">Make decisions together</p><p className="mt-2 text-xs leading-5 text-slate-500">Invite someone you trust to review a report with you. Sharing always starts with your consent.</p><Link href="/family" className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-teal-700">Invite family <ArrowUpRight className="size-3.5" /></Link></div> : <div className="mt-5 flex flex-col gap-2">{sharedWithMe.map((item) => <Link key={item.id} href={`/analyze/${item.id}`} className="rounded-xl border border-slate-200 p-3 hover:border-teal-300 hover:bg-teal-50/40"><div className="flex items-center justify-between gap-2"><span className="truncate text-xs font-semibold text-slate-800">{item.title}</span><span className="shrink-0 rounded-full bg-teal-50 px-2 py-1 text-[10px] font-semibold text-teal-800">Shared</span></div><span className="mt-1 block text-[11px] text-slate-500">From {item.ownerDisplayName || "a family member"}</span></Link>)}</div>}</section><section className="rounded-2xl border border-teal-100 bg-teal-50/70 p-5 sm:p-6"><div className="flex items-center gap-2 text-teal-900"><CheckCircle2 className="size-4 text-teal-700" /><h2 className="text-sm font-semibold">Our truth commitments</h2></div><ul className="mt-4 flex flex-col gap-3 text-xs leading-5 text-teal-950/75"><li><strong className="text-teal-950">Neutral, always.</strong> No mortgage sales, sponsored rankings, or commissions.</li><li><strong className="text-teal-950">Consent first.</strong> You decide what is shared and who can see it.</li><li><strong className="text-teal-950">Clarity over confidence.</strong> We surface questions, not promises.</li></ul></section><Link href="/calculator" className="surface-card group flex items-center justify-between p-5 hover:border-teal-200"><div><p className="eyebrow">Plan ahead</p><p className="mt-1 text-sm font-semibold text-slate-800">Explore your repayment</p><p className="mt-1 text-xs text-slate-500">Run a calm what-if scenario.</p></div><span className="flex size-9 items-center justify-center rounded-xl bg-slate-50 text-slate-500 transition-colors group-hover:bg-teal-50 group-hover:text-teal-700"><Calculator className="size-4" /></span></Link></aside></div>
  </main></div>;
}
